# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2740ebc301fa51cc891d38aa8df2b6135c9e2fd2243d05ecf30cbbf7722fad7be128125850cd4c181775d691ec99397de2687c45282a0dc4055612e98609511d

test:
  secret_key_base: 1c3540b5f0567643310b1069d9d7e09767b979be21a923ed000234a1c1eceef1ff142bc702ccbf24031d0e55b12cf38c94061034422d652f1f3d9c74a071777b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
